on:
  push:
    branches: [ master, stable* ]
  pull_request:
    branches: [ master, stable* ]
    
jobs:
  build_job:
    runs-on: ubuntu-latest
    name: "Test on ${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        arch: [armv7, aarch64, riscv64, s390x, ppc64le]
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@master
        name: "Run tests"
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y \
              libxrandr-dev \
              libxinerama-dev \
              libusb-1.0-0-dev \
              xserver-xorg-dev \
              libswscale-dev \
              libswresample-dev \
              libavutil-dev \
              libavcodec-dev \
              libcups2-dev \
              libpulse-dev \
              libasound2-dev \
              libpcsclite-dev \
              xsltproc \
              libxcb-cursor-dev \
              libxcursor-dev \
              libcairo2-dev \
              libfaac-dev \
              libfaad-dev \
              libjpeg-dev \
              libgsm1-dev \
              ninja-build \
              libxfixes-dev \
              libxkbcommon-dev \
              libwayland-dev \
              libpam0g-dev \
              libxdamage-dev \
              libxcb-damage0-dev \
              libxtst-dev \
              libfuse3-dev \
              libsystemd-dev \
              libcairo2-dev \
              libsoxr-dev \
              libsdl2-dev \
              docbook-xsl \
              libkrb5-dev \
              libcjson-dev \
              libpkcs11-helper1-dev \
              libsdl2-ttf-dev \
              libwebkit2gtk-4.0-dev \
              libopus-dev \
              liburiparser-dev \
              cmake
          run: |
            mkdir ci-build
            cd ci-build
            cmake -GNinja -C ../ci/cmake-preloads/config-linux-all.txt -DWITH_SANITIZE_ADDRESS=OFF ..
            cmake --build . -j$(nproc)
            ctest -j$(nproc) --output-on-failure -E TestConnect
